server.port=${APP_PORT:18080}
spring.application.name=northwind-platform
spring.main.banner-mode=off
spring.jackson.default-property-inclusion=non_null
server.error.include-message=always
logging.level.root=WARN
logging.level.nw=INFO
